branch-defaults:
  master:
    environment: cloud-dev-project-2-udagram-image-filte
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: cloud-dev-project-2-udagram-image-filter
  branch: null
  default_ec2_keyname: udagram-restapi-ec2-key-pair
  default_platform: Node.js
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
